# Generated by Django 4.2.23 on 2025-06-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='amir', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(null=True, upload_to='slides/blog/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='review',
            field=models.IntegerField(default=0),
        ),
    ]
